export const ADD_TODO = "ADD_TODO";
export const GET_TODOS = "GET_TODOS";
export const DELETE_TODO = "DELETE_TODO";

export const UPDATE_FETCH_PHRASE__START = "UPDATE_FETCH_PHRASE__START";
export const UPDATE_FETCH_PHRASE__FAILURE = "UPDATE_FETCH_PHRASE__FAILURE";
